name: dental
description: "Dental Apps"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  logger:
  uuid:
  intl: any
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  go_router: ^14.8.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.3
  envied: ^0.5.2
  flutter_localizations:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  liquid_progress_indicator_v2: ^0.5.0
  # font_awesome_flutter: ^10.6.0
  flutter_staggered_grid_view: ^0.7.0
  # hooks_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  # geolocator: ^10.1.0
  # geocoding: ^3.0.0
  shimmer: ^3.0.0
  flutter_hooks: ^0.20.4
  connectivity_plus: ^6.0.5
  # vector_math: ^2.1.4
  # flutter_compass: ^0.8.0
  # stream_transform: ^2.1.0
  sliding_up_panel:
    git:
      url: https://github.com/antho-firuze/sliding_up_panel.git
  # flutter_qiblah:
  #   git:
  #     url: https://github.com/antho-firuze/flutter_qiblah.git
  # google_maps_flutter: ^2.9.0
  # google_maps_flutter_android: ^2.14.0
  # google_maps_flutter_platform_interface: ^2.9.0
  # wiredash: ^1.9.0
  # supabase_flutter: ^2.2.0
  package_info_plus:
  device_info_plus: ^10.1.2
  network_info_plus: ^6.0.1
  disable_battery_optimization: ^1.1.1
  permission_handler: ^11.1.0
  avatar_glow: ^3.0.1
  # mic_stream: ^0.7.1+2
  # flutter_sound: ^9.6.0
  # audio_session: ^0.1.18
  # awesome_notifications: ^0.9.0
  async: ^2.11.0
  path_provider: ^2.1.2
  # flutter_archive: ^6.0.0
  flutter_local_notifications: ^17.2.2
  # wakelock_plus: ^1.1.4
  flutter_timezone: ^2.1.0
  timezone: ^0.9.2
  marquee: ^2.2.3
  # math_expressions: ^2.4.0
  # puppeteer: ^3.6.0
  # webview_flutter: ^4.4.4
  # xml: ^6.5.0
  flutter_spinkit: ^5.2.1
  camera: ^0.11.0+2
  image: ^4.2.0
  photo_manager: ^3.2.0
  photo_manager_image_provider: ^2.1.1
  flutter_image_compress: ^2.3.0
  share_plus: ^10.0.0
  flutter_widget_from_html: ^0.15.2
  # flutter_webrtc: ^0.11.6
  super_icons: ^1.0.3
  teeth_selector: 
    path: ../teeth-selector
  animated_toggle_switch: ^0.8.4
  table_calendar: ^3.1.3
  toggle_switch: ^2.3.0
  html: ^0.15.5
  age_calculator: ^1.0.0
    # git:
    #   url: https://github.com/antho-firuze/teeth-selector.git
  # pusher_channels_flutter: ^2.2.1
  # flutter_sticky_header: ^0.7.0
  # scroll_to_index: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  icons_launcher: ^2.1.7
  json_serializable: ^6.7.1
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.7

dependency_overrides:
  fading_edge_scrollview: ^4.1.1
#   intl: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/menu/
    - assets/icons/dental/
    - assets/images/
    - assets/json/
    - assets/sound/
  generate: true
  fonts:
    - family: diodrum
      fonts:
        - asset: assets/fonts/DiodrumArabic-Regular.ttf
        - asset: assets/fonts/DiodrumArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/DiodrumArabic-Semibold.ttf
          weight: 600
        - asset: assets/fonts/DiodrumArabic-Bold.ttf
          weight: 700
    - family: uthmanic
      fonts:
        - asset: assets/fonts/UthmanicHafs-Regular.ttf
        - asset: assets/fonts/UthmanicHafs-Bold.ttf
          weight: 700
icons_launcher:
  platforms:
    android:
      enable: true
      image_path: "assets/icons/app-icon.png"
    ios:
      enable: true
      image_path: "assets/icons/app-icon-ios.png"
